version: "3.9"  # optional since v1.27.0
services:
  signing_ms:
    container_name: firma_signing_ms    
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./public:/var/www/html/
      - ./src:/var/www/src/
      - ./tests:/var/www/tests/
    ports:
      - 8092:80
    extra_hosts:
      - host.docker.internal:host-gateway

